name: Trigger auto deployment for ca-cooking-assistant

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ claude/connect-cooking-assistant-SYAxz ]
    paths:
    - '**'
    - '.github/workflows/ca-cooking-assistant-AutoDeployTrigger-08ae4d32-87d1-4f61-83da-1854c6c2ba42.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CACOOKINGASSISTANT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CACOOKINGASSISTANT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CACOOKINGASSISTANT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrcookingassistant-chfyhjfef8a2e6aa.azurecr.io
          registryUsername: ${{ secrets.CACOOKINGASSISTANT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CACOOKINGASSISTANT_REGISTRY_PASSWORD }}
          containerAppName: ca-cooking-assistant
          resourceGroup: rg-cooking-assistant
          imageToBuild: acrcookingassistant-chfyhjfef8a2e6aa.azurecr.io/ca-cooking-assistant:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


